# Generated by Django 4.1.5 on 2024-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPolls',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('media_content', models.CharField(max_length=2000)),
                ('number_of_participation', models.CharField(max_length=50)),
                ('number_of_engagement', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('pollsID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('duration_from', models.DateTimeField(max_length=20)),
                ('duration_to', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('profile_image', models.CharField(max_length=2000)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VotingUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pollID', models.CharField(max_length=50)),
                ('tagname', models.CharField(max_length=50)),
            ],
        ),
    ]
